name: Deploy to o2switch

on:
  push:
    branches:
      - main   # adapte si ta branche par défaut est master ou autre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug host
      run: |
        echo "SSH_HOST=${{ secrets.SSH_HOST }}"
        ping -c 3 ${{ secrets.SSH_HOST }}

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy files
      run: |
        rsync -avz --delete \
          --exclude ".git" \
          --exclude ".github" \
          --exclude "node_modules" \
          ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/www/
